//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentOpening
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string Qualification { get; set; }
        public string SkillSet { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OpenTillDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
