//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public Download()
        {
            this.DownloadAttachments = new HashSet<DownloadAttachment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DownloadPath { get; set; }
    
        public virtual ICollection<DownloadAttachment> DownloadAttachments { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
    }
}
