//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Pages = new HashSet<Page>();
            this.Menus1 = new HashSet<Menu>();
        }
    
        public int Id { get; set; }
        public string MenuName { get; set; }
        public int DisplayOrderId { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual Menu Menu1 { get; set; }
    }
}
