//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int MenuId { get; set; }
        public string Content { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public short Status { get; set; }
        public string SeoTitle { get; set; }
        public string MetaKeys { get; set; }
        public string Description { get; set; }
        public string H1 { get; set; }
        public string H2 { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual User User { get; set; }
    }
}
