//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.PermissionsInRoles = new HashSet<PermissionsInRole>();
        }
    
        public int Id { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PermissionsInRole> PermissionsInRoles { get; set; }
    }
}
