//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGallery
    {
        public PhotoGallery()
        {
            this.PhotoGalleryAttachments = new HashSet<PhotoGalleryAttachment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Path { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual SectionMaster SectionMaster { get; set; }
        public virtual ICollection<PhotoGalleryAttachment> PhotoGalleryAttachments { get; set; }
    }
}
