//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.SectorAttachments = new HashSet<SectorAttachment>();
            this.Sectors1 = new HashSet<Sector>();
        }
    
        public int Id { get; set; }
        public string SectorName { get; set; }
        public Nullable<int> ParentSectorId { get; set; }
    
        public virtual ICollection<SectorAttachment> SectorAttachments { get; set; }
        public virtual ICollection<Sector> Sectors1 { get; set; }
        public virtual Sector Sector1 { get; set; }
    }
}
